[package]
name = "ship_compliant_v2_rb"
version = "0.1.0"
edition = "2021"
authors = ["Julian Giamblanco <giamblanco.julian@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6" }
